[package]
name = "guessing_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
guessing_game_lib = { path = "../guessing_game_lib" }
regex = "1.9.6"
