[package]
name = "recipe_manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clearscreen = "2.0.1"
recipe_manager_lib = { path = "../recipe_manager_lib" }
