[package]
name = "async_web_scraper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web_scrape_lib = { path = "../web_scrape_lib" }
tokio = { version = "1.33.0" , features = ["full"] }