[package]
name = "crawler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crawlerlib = { path = "../crawlerlib" }
texting_robots = "0.2.2"
tokio = { version = "1.33.0" , features = ["full"] }
